using PolicyManagement.Data;
using PolicyManagement.Enums;
using PolicyManagement.Models.PaymentManagement;
using QuestPDF.Fluent;

namespace PolicyManagement.Service.PaymentManagement
{
    public class InvoiceService : IInvoiceService
    {
        private readonly AppDbContext _context;

        public InvoiceService(AppDbContext context)
        {
            _context = context;
        }

        public Invoice GenerateInvoice(string paymentId, string userId)
        {
            var payment = _context.Payment.FirstOrDefault(p =>
                p.PaymentId == paymentId);

            if (payment == null)
                throw new KeyNotFoundException("Payment not found.");

            if (payment.Status != PaymentStatus.SUCCESSFUL)
                throw new Exception("An invoice can only be generated for a successful payment.");

            var existingInvoices = _context.Invoice.ToList();
            int nextNumber = existingInvoices.Any()
                ? existingInvoices.Max(i =>
                {
                    var numericPart = i.InvoiceRef.Replace("INV", "");
                    return int.TryParse(numericPart, out var num) ? num : 0;
                }) + 1
                : 1;

            string invoiceReference = $"INV{nextNumber:D6}";

            string invoicesFolder = Path.Combine(
                Directory.GetCurrentDirectory(),
                "wwwroot",
                "invoices");

            if (!Directory.Exists(invoicesFolder))
            {
                Directory.CreateDirectory(invoicesFolder);
            }

            string fileName = $"{invoiceReference}.pdf";

            string relativePath = Path.Combine("wwwroot", "invoices", fileName);
            string fullPath = Path.Combine(Directory.GetCurrentDirectory(), relativePath);

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Text("PAYMENT INVOICE")
                        .FontSize(24)
                        .Bold()
                        .AlignCenter();

                    page.Content().Column(column =>
                    {
                        column.Spacing(8);
                        column.Item().Text($"Invoice Reference: {invoiceReference}");
                        column.Item().Text($"Invoice Date: {DateTime.Now:dd MMM yyyy}");
                        column.Item().Text($"Payment ID: {payment.PaymentId}");
                        column.Item().Text($"Amount Paid: R{payment.Amount:N2}");
                        column.Item().Text($"Payment Method: {payment.Method}");
                        column.Item().Text($"Payment Status: {payment.Status}");
                        column.Item().PaddingTop(20);
                        column.Item().Text("Thank you for your payment.").Italic();
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by Funeral Management System");
                });
            })
            .GeneratePdf(fullPath);

            var invoice = new Invoice(
                invoiceReference,
                payment.PaymentId,
                userId,
                relativePath
            );

            _context.Invoice.Add(invoice);
            _context.SaveChanges();

            return invoice;
        }

        public Invoice GetInvoiceById(string invoiceId, string userId)
        {
            var invoice = _context.Invoice.FirstOrDefault(i =>
                i.InvoiceId == invoiceId &&
                i.UserId == userId);

            if (invoice == null)
                throw new KeyNotFoundException("Invoice not found.");

            return invoice;
        }

        public Invoice GetInvoiceByPaymentId(string paymentId, string userId)
        {
            var invoice = _context.Invoice.FirstOrDefault(i =>
                i.PaymentId == paymentId &&
                i.UserId == userId);

            if (invoice == null)
                throw new KeyNotFoundException("Invoice not found for this payment.");

            return invoice;
        }

        public FileInfo DownloadInvoice(string invoiceId, string userId)
        {
            var invoice = GetInvoiceById(invoiceId, userId);

            string fullPath = Path.Combine(Directory.GetCurrentDirectory(), invoice.PdfPath);

            if (!File.Exists(fullPath))
                throw new FileNotFoundException("Invoice PDF not found.");

            return new FileInfo(fullPath);
        }

        public Invoice GenerateInvoiceFromPayment(string paymentId, string userId)
        {
            var payment = _context.Payment
                .FirstOrDefault(p => p.PaymentId == paymentId);

            if (payment == null)
                throw new KeyNotFoundException($"Payment {paymentId} not found.");

            var existingInvoice = _context.Invoice.FirstOrDefault(i =>
                i.PaymentId == paymentId);

            if (existingInvoice != null)
                throw new InvalidOperationException("Invoice already exists for this payment.");

            return GenerateInvoice(paymentId, userId);
        }
    }
}