name: Build and deploy ASP.Net Core app to Azure Web App - legacycare-api-2026

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build "legacycare_backend/legacycare_backend/PolicyManagement.csproj" --configuration Release

      - name: Publish with dotnet
        run: dotnet publish "legacycare_backend/legacycare_backend/PolicyManagement.csproj" --configuration Release --output "${{ env.DOTNET_ROOT }}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_50E38E72035F42289C8FC1DFFCE9A98C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_914E4588241140BF8DDED8962F5D3946 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE01F9F258AB4CA9ABBC949779BCCD6B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'legacycare-api-2026'
          slot-name: 'Production'
          package: .
